[project]
name="DJ Music App"
version="1.0.0"

[general]
enabled_commands=[
  "downloadMusicList",
  "audioMigration",
  "localMusicSearch",
  "convertToALAC",
  "getYouTubeUrls",
  "search_1001tracklists",
  "cleanMetadata",
  "getSongInfo"
]
